### ISSUE TITLE
Failing tests?

### ISSUE THREAD

**Issue by AlexKnauth** [oflatt/space-orbs#12]
When I run the tests in `current-roll-and-pos.rkt`, I get a bunch of failures. At first I thought they were my fault and that I did something wrong with trying to refactor, but they fail without my changes as well.

(Selfishness: I want working tests so that I know my refactoring won't change any of the current behavior.)

**Comment by AlexKnauth** [comment]
I also get a failure when running the tests in `collision-detection.rkt`.

**Comment by oflatt** [comment]
Oh, I will look into that sometime sorry

**Comment by oflatt** [comment]
I finally figured out that it was the FINAL-LANDSCAPE given to movement collision that was causing the problems with the current-roll-and-pos tests. I will fix it by making the tests in the middle of the empty room.

**Comment by oflatt** [comment]
OK, I fixed tests in both modules you mentioned, I will push it

**Comment by AlexKnauth** [comment]
Thanks!
