### ISSUE TITLE
dir: expected rational coordinates; given +nan.0 +nan.0 +nan.0

### ISSUE THREAD

**Issue by AlexKnauth** [oflatt/space-orbs#24]
I just got an error message like this:

```
. . rotate-dir.rkt:63:21: dir: expected rational coordinates; given +nan.0 +nan.0 +nan.0
```

It also happened to both of us while playing so it might involve something that's sent through the server.

**Comment by oflatt** [comment]
Hmm, weird. I don't know why that happened. The server checks for bad messages but does not check if they are all real numbers

**Comment by AlexKnauth** [comment]
Ok, I've done some experiments and it looks like using `rotate-up` on a zero-dir does this:

``` racket
> (rotate-up (dir 0 0 0))
. . dir: expected rational coordinates; given +nan.0 +nan.0 +nan.0
> (dir->angles (dir 0 0 0))
0.0
+nan.0
> (angles->dir 0.0 +nan.0)
. . dir: expected rational coordinates; given +nan.0 +nan.0 +nan.0
```

Because `dir->angles` returns `+nan.0` for the second angle.
