### ISSUE TITLE
Is shooting through cubes supposed to work?

### ISSUE THREAD

**Issue by AlexKnauth** [oflatt/space-orbs#28]
Is shooting through cubes supposed to work?

**Comment by oflatt** [comment]
Nope

**Comment by oflatt** [comment]
Would you like it to? That would be an interesting idea

**Comment by AlexKnauth** [comment]
Um, not really, but me and my friend tried it and we could shoot each other through the cubes. The laser thing stops at the cube, but we could still shoot each other through them.

**Comment by oflatt** [comment]
Ohh, that's a new bug that can be easily fixed. Sorry I am so busy I will
try to find time
